import sys
sys.path.append(r'/home/irene/Eclipse/workspace/Demo/atdb/Install/Download/')
import GetPackages
obj = GetPackages.GetPackages()
obj.getLastDEBServer()
obj.getLastDEBAgent()
obj.getLastRPMAgent()
obj.getLastAIXAgent()
obj.getReleaseDEBServer()
obj.getReleaseDEBAgent()
obj.getReleaseRPMAgent()
obj.getReleaseAIXAgent()
obj.getLastDEBServer3()
obj.getLastRPMDBackup3()
obj.getLastPPCDBackup3()
obj.getReleaseDEBServer3()
obj.getReleaseRPMDBackup3()
obj.getReleasePPCDBackup3()
obj.getLastMIPS64DBackup3()
